sudo: required
language: php
services:
  - docker
install:
  - mkdir -p ~/.composer
  - echo "${AUTH_JSON}" > ~/.composer/auth.json
  - sudo curl -L https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - (cd .docker; docker-compose up -d;)
  - docker exec -it local_dev_web bash -c 'cd /var/www/html; ./install.sh'

script:
  - echo "It Works!"
